/* CMS PROC CD Starts */

CREATE TABLE EMPLOYEE
(
    employee_id VARCHAR(15) NOT NULL,
    employee_name VARCHAR(50) NOT NULL,
    creat_dttm TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creat_user_id VARCHAR(250) NULL,
    chg_dttm TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    chg_user_id VARCHAR(250) NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (employee_id)
);