version: '3.6'
services:
  postgres:
    image: postgres
    container_name: Postgres_Local_Setup_Container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./dbFiles/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - postgres_data:/var/lib/postgresql/data
      - ./dbFiles/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./dbFiles/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "7878:5432"
volumes:
  postgres_data: